#!/usr/bin/env python3
"""Strip personal and customer data out of the debug reports before they are
committed.

These files are generated by the db-check workflow and committed to the repo so
the result can be read without downloading a run log. That makes them a standing
hazard: a `select *` in a future edit puts driver signatures, names, plates and
customer tracking numbers into version control, where removing them again means
rewriting history. The queries name their columns; this is the second line of
defence, in case one day they do not.
"""
import re
import sys

RULES = [
    # Driver signatures and rendered documents, embedded as data URLs.
    (re.compile(r"data:image/[a-z+]+;base64,[A-Za-z0-9+/=]+"), "<image redacted>"),
    (re.compile(r"data:application/pdf[;,][^\"'\s]*"), "<pdf redacted>"),
    # Whole lists of customer tracking numbers, from the manifest endpoints.
    (re.compile(r'"tracking_ids"\s*:\s*\[[^\]]*\]'), '"tracking_ids":[ redacted ]'),
    # Individual fields in JSON payloads.
    # `name` and `label` carry people: the drivers endpoint returns
    # {"name":"<a driver>",...} and the badge lookup {"label":"<an operator>"}.
    (re.compile(r'"(tracking|code|driverName|driver_name|plate|operator|operatorName|name|label|courierCompany|ip)"\s*:\s*"[^"]*"'),
     r'"\1":"<redacted>"'),
    # psql's expanded output, "column | value" one per line.
    (re.compile(r"^(driver_name|driver_plate|plate|tracking|operator|label)(\s*\|).*$", re.M),
     r"\1\2 <redacted>"),
    # psql's default table layout: the badge roster is "badge | country | name",
    # so redacting only the badge would leave the operator's name beside it.
    (re.compile(r"^\s*BADGE-[A-Z0-9-]+\s*\|.*$", re.M), " <badge row redacted>"),
    (re.compile(r"BADGE-[A-Z0-9-]+"), "<badge redacted>"),
    # Login-audit IP addresses. Personal data, and of no use in a debug report.
    (re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b"), "<ip redacted>"),
]


def scrub(text):
    for pattern, replacement in RULES:
        text = pattern.sub(replacement, text)
    return text


def main(paths):
    for path in paths:
        try:
            original = open(path, encoding="utf-8", errors="replace").read()
        except FileNotFoundError:
            continue
        cleaned = scrub(original)
        if cleaned != original:
            open(path, "w", encoding="utf-8").write(cleaned)
            print(f"scrubbed {path}: {len(original) - len(cleaned)} bytes removed")
        else:
            print(f"{path}: nothing to scrub")


if __name__ == "__main__":
    main(sys.argv[1:])
